package com.example.bluecodepay.model.enums;

public enum ErrorCode {
    INVALID_PARAMETER,
    BRANCH_NOT_FOUND,
    MERCHANT_TX_ID_NOT_UNIQUE,
    UNAUTHORIZED,
    TRANSACTION_NOT_FOUND,
    CANCEL_PERIOD_EXPIRED,
    CANCEL_NOT_SUPPORTED,
    SYSTEM_FAILURE,
    AMOUNT_TOO_HIGH,
    ISSUER_FAILURE,
    REFUND_PERIOD_EXPIRED,
    INVALID_REQUEST
}
